AllCops:
  Include:
    - 'Gemfile'
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'config/**/*.rb'
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'features/**/*.rb'
    - 'script/**/*.rb'
    - 'spec/**/*.rb'
    - 'vendor/**/*'

Style/SelfAssignment: # good to be enabled
  Enabled: false

Style/NestedTernaryOperator: # good to be enabled
  Enabled: false

Style/PredicateName: # good to be enabled
  Enabled: false

Style/AccessorMethodName: # good to be enabled
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/BlockNesting: # good to be enabled
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
